name: CI

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      matrix:
        container: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        
    steps:
      - uses: actions/checkout@v3
      - name: echo container
        run: echo ${{ matrix.container }}
