name: CI

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo hello world
        run: echo HELLO WORLD! ✅
        
  build:
    needs: prepare
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      matrix:
        container: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        
    steps:
      - uses: actions/checkout@v3
      - name: echo container
        run: echo ${{ matrix.container }}
